/* LOGIN */
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

/* EXTERNAL LOGIN */
export const GOT_EXTERNAL_LOGINS = 'GOT_EXTERNAL_LOGINS'
export const EXTERNAL_LOGIN_START = 'EXTERNAL_LOGIN_START'

/* SIGNUP */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const SIGNUP_TYPE = 'SIGNUP_TYPE'
export const SENT_PASSWORD_RESET_TOKEN_SUCCESS = 'SENT_PASSWORD_RESET_TOKEN_SUCCESS'
export const SENT_PASSWORD_RESET_TOKEN_FAILURE = 'SENT_PASSWORD_RESET_TOKEN_FAILURE'
export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS'
export const SET_NEW_PASSWORD_FAILURE = 'SET_NEW_PASSWORD_FAILURE'

/* TALENT */
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE'
export const PROFILE_STEP_1_SUCCESS = 'PROFILE_STEP_1_SUCCESS'
export const PROFILE_STEP_1_FAILURE = 'PROFILE_STEP_1_FAILURE'
export const GET_ROLES_TECH = 'GET_ROLES_TECH'
export const GET_SUBMITION_DATA = 'GET_SUBMITION_DATA'
export const UPDATE_STATUS = 'UPDATE_STATUS'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS'

/* USER */
export const EDIT_TYPE = 'EDIT_TYPE'

